"""Add password_hash field to users

Revision ID: 0cb047f4a441
Revises: 5c616275cc70
Create Date: 2026-03-04 12:04:59.887840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb047f4a441'
down_revision: Union[str, None] = '5c616275cc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'national_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_national_id_key', 'users', type_='unique')
    op.drop_index('ix_users_national_id', table_name='users')
    op.create_index(op.f('ix_users_national_id'), 'users', ['national_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_national_id'), table_name='users')
    op.create_index('ix_users_national_id', 'users', ['national_id'], unique=False)
    op.create_unique_constraint('users_national_id_key', 'users', ['national_id'])
    op.alter_column('users', 'national_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
