"""Initial migration with all tables and indexes

Revision ID: be67793cedd3
Revises: 
Create Date: 2026-01-16 11:20:06.283823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be67793cedd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    
    # Create repayments table
    op.create_table('repayments',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('loan_reference', sa.String(length=100), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('payment_date', sa.Date(), nullable=False),
        sa.Column('status', sa.Enum('on_time', 'late', name='repaymentstatus'), nullable=False),
        sa.Column('days_overdue', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayments_created_at'), 'repayments', ['created_at'], unique=False)
    op.create_index(op.f('ix_repayments_user_id'), 'repayments', ['user_id'], unique=False)
    
    # Create mpesa_transactions table
    op.create_table('mpesa_transactions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('transaction_type', sa.Enum('incoming', 'outgoing', name='transactiontype'), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('reference', sa.String(length=100), nullable=False),
        sa.Column('transaction_date', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_transactions_created_at'), 'mpesa_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_user_id'), 'mpesa_transactions', ['user_id'], unique=False)
    
    # Create fines table
    op.create_table('fines',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('reason', sa.String(length=500), nullable=False),
        sa.Column('status', sa.Enum('unpaid', 'paid', name='finestatus'), nullable=False),
        sa.Column('assessed_date', sa.Date(), nullable=False),
        sa.Column('paid_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_created_at'), 'fines', ['created_at'], unique=False)
    op.create_index(op.f('ix_fines_user_id'), 'fines', ['user_id'], unique=False)
    
    # Create payments table
    op.create_table('payments',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('payment_type', sa.Enum('repayment', 'fine', 'other', name='paymenttype'), nullable=False),
        sa.Column('status', sa.Enum('completed', 'pending', 'failed', name='paymentstatus'), nullable=False),
        sa.Column('payment_date', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    
    # Create credit_scores table
    op.create_table('credit_scores',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(length=20), nullable=False),
        sa.Column('repayment_factor', sa.Float(), nullable=False),
        sa.Column('mpesa_factor', sa.Float(), nullable=False),
        sa.Column('consistency_factor', sa.Float(), nullable=False),
        sa.Column('fine_factor', sa.Float(), nullable=False),
        sa.Column('calculated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_scores_user_id'), 'credit_scores', ['user_id'], unique=False)
    op.create_index('ix_credit_scores_user_calculated', 'credit_scores', ['user_id', 'calculated_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order
    op.drop_index('ix_credit_scores_user_calculated', table_name='credit_scores')
    op.drop_index(op.f('ix_credit_scores_user_id'), table_name='credit_scores')
    op.drop_table('credit_scores')
    
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    
    op.drop_index(op.f('ix_fines_user_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_created_at'), table_name='fines')
    op.drop_table('fines')
    
    op.drop_index(op.f('ix_mpesa_transactions_user_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_created_at'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    
    op.drop_index(op.f('ix_repayments_user_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_created_at'), table_name='repayments')
    op.drop_table('repayments')
    
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###
