"""Add system_users and credit_subjects tables

Revision ID: d96673d77997
Revises: 0cb047f4a441
Create Date: 2026-03-05 11:01:50.933957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd96673d77997'
down_revision: Union[str, None] = '0cb047f4a441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create system_users table
    op.create_table('system_users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_system_users_email'), 'system_users', ['email'], unique=False)
    
    # Create credit_subjects table
    op.create_table('credit_subjects',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('national_id', sa.String(length=50), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_subjects_external_id'), 'credit_subjects', ['external_id'], unique=False)
    op.create_index(op.f('ix_credit_subjects_national_id'), 'credit_subjects', ['national_id'], unique=False)
    op.create_index(op.f('ix_credit_subjects_phone_number'), 'credit_subjects', ['phone_number'], unique=False)
    op.create_index(op.f('ix_credit_subjects_email'), 'credit_subjects', ['email'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_subjects_email'), table_name='credit_subjects')
    op.drop_index(op.f('ix_credit_subjects_phone_number'), table_name='credit_subjects')
    op.drop_index(op.f('ix_credit_subjects_national_id'), table_name='credit_subjects')
    op.drop_index(op.f('ix_credit_subjects_external_id'), table_name='credit_subjects')
    op.drop_table('credit_subjects')
    op.drop_index(op.f('ix_system_users_email'), table_name='system_users')
    op.drop_table('system_users')
    # ### end Alembic commands ###
